FROM jenkins/jenkins
USER root
# Modificamos para instalar dependencias de python para utilizar correctamente jenkins
RUN apt-get update && apt-get install -y \ 
    lsb-release \
    python3 \
    python3-pip

RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
https://download.docker.com/linux/debian/gpg
RUN echo "deb [arch=$(dpkg --print-architecture) \
signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
https://download.docker.com/linux/debian \
$(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
RUN apt-get update && apt-get install -y docker-ce-cli

# Instalamos dependencias
RUN pip3 install --break-system-packages pytest pytest pyinstaller

USER jenkins
RUN jenkins-plugin-cli --plugins "blueocean docker-workflow"